apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: true
    image:
      repository: gitea/gitea
      tag: 1.19-dev-linux-arm64
    env:
      - name: USER_UID
        value: "1024"
      - name: USER_GID
        value: "100"
      - name: GITEA__database__DB_TYPE
        value: mysql
      - name: GITEA__database__HOST
        value: srv-db.lan:3306
      - name: GITEA__database__NAME
        value: gitea
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: gitea-db
            key: login
      - name: GITEA__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-db
            key: password
      - name: GITEA__service__DISABLE_REGISTRATION
        value: "true"
      - name: GITEA__service__REQUIRE_SIGNIN_VIEW
        value: "true"
      - name: GITEA__mailer__ENABLED
        value: "true"
      - name: GITEA__mailer__FROM
        value: "gitea@angrybits.pl"
      - name: GITEA__mailer__MAILER_TYPE
        value: "smtp"
      - name: GITEA__mailer__SMTP_ADDR
        value: "smtp-service-smtp-svc.default.svc.cluster.local"
      - name: GITEA__mailer__SMTP_PORT
        value: "25"
      - name: GITEA__mailer__IS_TLS_ENABLED
        value: "false"
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
      requests:
        memory: 1Gi
        cpu: 600m
    services:
      - name: http
        servicePort: 80
        targetPort: 3000
      - name: ssh
        servicePort: 2222
        targetPort: 22
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: gitea.angrybits.pl
      tls:
        - hosts:
            - gitea.angrybits.pl
    volumes:
      enabled: true
      mountPath:
        - gitea:/var/lib/gitea
        - config:/etc/gitea
        - data:/data
      ownership: 1024:100
      type:
        nfs:
          server: srv-nfs.lan
          path: /storage
